#!/usr/bin/env bash

CONTAINER_MONGO_HOST=$(set | egrep "MONGO[0-9]+_SERVICE_HOST" | cut -d'=' -f2)

if [ ! -z $CONTAINER_MONGO_HOST ]; then
    ME_CONFIG_MONGODB_SERVER=$CONTAINER_MONGO_HOST
    echo "Using dynamic mongo host setting"
fi

if [ ! -z $ME_CONFIG_MONGODB_SERVER ]; then
    echo "Mongo db host is ''$ME_CONFIG_MONGODB_SERVER' - enabling mongo express..."
    sed "s/<ME_CONFIG_MONGODB_SERVER>/$ME_CONFIG_MONGODB_SERVER/" /etc/supervisor/conf.d/mongoexpress.conf.template > /etc/supervisor/conf.d/mongoexpress.conf
else
    echo "ME_CONFIG_MONGODB_SERVER not set - not enabling mongo express"
fi
