#!/usr/bin/env bash

if [ ! -z $ME_CONFIG_MONGODB_SERVER ]; then
    echo "Mongo db host is ''$ME_CONFIG_MONGODB_SERVER' - enabling mongo express..."
    mv /etc/supervisor/conf.d/mongoexpress.conf.template /etc/supervisor/conf.d/mongoexpress.conf
else
    echo "ME_CONFIG_MONGODB_SERVER not set - not enabling mongo express"
fi
